### ISSUE TITLE
Dude, how can I make friend with you? :V

### ISSUE THREAD

**Issue by alexhoanghtd** [sessamekesh/IndigoCS-webgl-tutorials#2]

**Comment by sessamekesh** [comment]
Aww, I'm flattered! Well I'm on GitHub and YouTube pretty frequently. I'd drop you my personal email address, but I'm not sure I'm comfortable doing that on the publicly accessible web.

**Comment by alexhoanghtd** [comment]
yeah, I followed you on youtube :D I did think about it, but anyways, my email is Alex@onteractive.eu can you please send me a message on that email, then I will delete this issue :3 thanks man :D
