### ISSUE TITLE
How to translation 05 - Phong Lighting Intro plz

### ISSUE THREAD

**Issue by Ali1Jamal** [sessamekesh/IndigoCS-webgl-tutorials#6]
Hello:
i need to constant translation 05 - Phong Lighting Intro ..i try to use mat4 but dosent work for me. can you show me how to translate it please?

**Comment by sessamekesh** [comment]
What do you mean by translate? If you're trying to implement that code in a different language, you'll have to use a different math library.

GLM is good for C/C++, and is the math library that gl-matrix (mat4) is based on.

If you're using Java, Python, Go, etc., I'm not sure what libraries exist out there. Google "OpenGL math library [language]" and you should be able to find one that works similarly.

**Comment by Ali1Jamal** [comment]
I am sorry for my wrong writing ...
I meant constant translation

**Comment by Ali1Jamal** [comment]
i ask here https://stackoverflow.com/questions/52971138/webgl-translate-javascript 
But I did not find the solution
