### ISSUE TITLE
(minor issue) Global var that was intended to be local

### ISSUE THREAD

**Issue by jakedanczyk** [sessamekesh/IndigoCS-webgl-tutorials#7]
Kamaron,
In the second tutorial, towards the end you moved `var gl` to global, in order to [test some stuff in the browser console](https://www.youtube.com/watch?v=3yLL9ADo-ko&t=35m5s).

It looks like this ended up in the source code, so I propose moving it back to local.

**Comment by jakedanczyk** [comment]
Realized you kept it global in the following tutorials so that may have been intentional, apologies for unnecessary issue if so

**Comment by sessamekesh** [comment]
Merged #8, it is better practice. I don't remember what my original intention was, this is a good change. Thanks for catching that and fixing it!
